name       : arc-firefox-theme
version    : '52.20170311'
release    : 14
source     :
    - https://github.com/horst3180/arc-firefox-theme/archive/52.20170311.tar.gz : e169a222b64aa776a08f740eccefadefb2a215ec2d684ea6f39f0795987b7c1d
license    : MPL-2.0
summary    : Arc GTK theme for the Firefox Web Browser
component  : desktop.theme
description: |
    Arc GTK theme for the Firefox Web Browser
rundeps    :
    - arc-gtk-theme
    - firefox
setup      : |
    ./autogen.sh
    %configure --enable-darker --enable-dark --enable-light
build      : |
    %make
install    : |
    %make_install
