name       : arc-firefox-theme
version    : 42.20151103
release    : 4
source     :
    - https://github.com/horst3180/arc-firefox-theme/archive/42.20151103.tar.gz : bc41d40bdb6ff0cad3698f9004aca12dbac5a97073c7ab6c8b93779c9d99e6d4
license    : MPL-2.0
summary    : Arc GTK theme for the Firefox Web Browser
description: |
    Arc GTK theme for the Firefox Web Browser
rundeps    :
    - arc-gtk-theme
    - firefox
setup      : |
    ./autogen.sh
    %configure --enable-darker --enable-dark --enable-light
build      : |
    %make
install    : |
    %make_install
