name       : arc-firefox-theme
version    : '49.20160919'
release    : 11
source     :
    - https://github.com/horst3180/arc-firefox-theme/archive/49.20160919.tar.gz : e635f00b82467290e1b6e8d2d93a0a395b5c4fc518c0a72c892043e49e283556
license    : MPL-2.0
summary    : Arc GTK theme for the Firefox Web Browser
description: |
    Arc GTK theme for the Firefox Web Browser
rundeps    :
    - arc-gtk-theme
    - firefox
setup      : |
    ./autogen.sh
    %configure --enable-darker --enable-dark --enable-light
build      : |
    %make
install    : |
    %make_install
