name       : arc-firefox-theme
version    : 44.20160126
release    : 6
source     :
    - https://github.com/horst3180/arc-firefox-theme/archive/44.20160126.tar.gz : b7aaffc7e0561534fd677b9e3795b204a67b43472264201a73cf0f2d7db662d5
license    : MPL-2.0
summary    : Arc GTK theme for the Firefox Web Browser
description: |
    Arc GTK theme for the Firefox Web Browser
rundeps    :
    - arc-gtk-theme
    - firefox
setup      : |
    ./autogen.sh
    %configure --enable-darker --enable-dark --enable-light
build      : |
    %make
install    : |
    %make_install
